name: Build RailsGoat Image

concurrency: staging

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: 
      - main
  workflow_dispatch:

jobs:
#   build-docker:
#     name: "Build the docker image"
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: "Checkout"
#         uses: actions/checkout@v2
        
        
  build-railsgoat-contrast:
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - uses: actions/checkout@v2
    - name: "Set up Ruby"
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: '2.6.5'
        bundler-cache: true
    
    - name: "Install dependancies"
      run: bundle install
      
    - name: "Configure database"
      run: rails db:setup
    
    - name: "Run tests"
      run: bundle exec rake
    
    - name: "Post a nice comment"
      uses: github-actions-up-and-running/pr-comment@v1.0.1
      with:
        # Message to comment
        message:  "Successfully built the railsgoat app"


# OLD 
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag railsgoat-contrast:$(date +%s)
    
#     - name: Run a command
#       run:  bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
