name: Build RailsGoat Image

concurrency: staging

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: '3.1'
        bundler-cache: true
    
    - name: Install dependancies
      run: bundle install
    
    - name: Run tests
      run: bundle exec rake
    

#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag railsgoat-contrast:$(date +%s)
    
#     - name: Run a command
#       run:  bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
